### ISSUE TITLE
following getting started guide gives errors

### ISSUE THREAD

**Issue by drx999** [seliumlabs/selium#128]
hi all i tried to use selium for the first time this week and i ran into a issue when following the steps in the getting started section. I should also say i am quite new to programming in rust  however when i do exactly what is says i end up getting a error at the certification generation step. it tells me this: could not find `codecs` in `selium`. i see a few possibility's here. Either I'm not understanding fully and i did something wrong. this seems likely, but i can't find out what i did wrong as i followed the guide step by step multiple times and both on a windows and a Linux system just to test. another possibility is that the getting started is outdated or it has some inaccuracies.

**Comment by petehayes102** [comment]
Hey @drx999, thanks for raising this. It's definitely my fault here - the Getting Started guide has become out of date and has led you astray. Apologies mate. I'll go through it this weekend and correct it, but in the interim check out the [Client examples](https://github.com/seliumlabs/selium/tree/release/client/examples). These are tested as part of the build so should always compile.

**Comment by petehayes102** [comment]
@drx999 All finished. The new guide should work file. If I've made any mistakes please reopen this and I'll address them ASAP. Thanks for using Selium! 🥳
